### ISSUE TITLE
Standalone version

### ISSUE THREAD

**Issue by benrubson** [jetwhiz/encfs4win#100]
Hi,

Could it be possible to make a standalone package, which does not need to run an installation process ?
Of course we would have to install Dokany, if it's not already installed.

I noticed that Dokany needs VC redist of 2017 (DokanSetup_redist.exe includes it).
Current version of encfs4win brings 2 versions of VC.
Perhaps it could simply be possible to use the version Dokany includes, so that standalone package will not have to include it ?

Thx 👍 

Ben

**Comment by jetwhiz** [comment]
I'm going to merge this issue into https://github.com/jetwhiz/encfs4win/issues/68 since they are both along the same lines (and have same goals).  

Would a zip including just the encfs executables and openssl libraries be a good solution to this (basically just the encfs directory in Program Files)?

**Comment by benrubson** [comment]
Yes I think that would be perfect, thank you @jetwhiz 👍
