### ISSUE TITLE
Mount-Points Problem Questions

### ISSUE THREAD

**Issue by cyberpunkbln** [jetwhiz/encfs4win#106]
Hello,

Unfortunately i can not use mountpoints to directorys with the actual versions from extFS, but i have questions about that:

1. Is it a try worth to check ne modern dokany-versions with that problem, before you complied again this?
2. When i use no filename-encryption its functioned, no folder create problem, give it other workarounds?
3. I don't understand the --reverse-mode (smile i'm totally confused about the reverse-mode)?

thx

PS: I try the following: reproduce the dm_crypt home directory only encryption from linux adapt to windows 10.  I mean only enrypt a directory in an user_home_dir Users\Username\encFSDir\verysecret.txt or Documents.encFS or sowhat. On Linux i use home-dir-enryption and i want this on windows 10.

**Comment by jetwhiz** [comment]
Hi @cyberpunkbln 

1. This is likely not a problem introduced by Dokany, but is more likely introduced by Windows itself.  The issue regarding this is still open in Dokany and is not yet mitigated on their side
2. If you're using no filename encryption (null) or Block32 filename encryption (the default for partitions created with encfs4win), then you might not experience these issues.  We still recommend mounting to a drive letter just to be on the safe side until this issue is fully mitigated, though. 
3. Usually with encfs, you have encrypted files stored on your drive and you want a temporary view of the decrypted files (while encfs is running).  In reverse mode, you have unencrypted files on your drive and want a temporary view of the encrypted files.  This is useful if you want unencrypted files on your computer but want to copy encrypted versions of the files to another computer or cloud storage.

**Comment by cyberpunkbln** [comment]
Hello @jetwhiz ,

1. Okay so i must wait if this problem can be solved. In the moment i must managed my encrypted personal files with an drive-letter. Are other Fuse4Win Projects worth a block like WinFsp?

2. When i use the paranoid default filename protection i have these issues, too? Make the paranoid settings something wrong? or should i test it again with default block32 filename encryption, what must i set when i manually set the paramteres with x excactly to bypass the these issues?

3. Oh very thx now i have it understand complete reverse-mode.
