### ISSUE TITLE
Q: Cross-platform compilation?

### ISSUE THREAD

**Issue by jon-blum** [jetwhiz/encfs4win#118]
# Environment
 * Windows version: 10
 * Processor architecture: 
 * Encfs4win version: 1.10.1-RC13
 * Dokan version (legacy, modern): modern

# Description 
I've been working on a tweaked version of encfs4win, integrated with our company's access-control system.  Now they want me to port it to Mac and Linux versions.  I've noticed there are still some #ifdef clauses in the code referring to Win32 and linux, but I'm not sure whether these are just holdovers from the EncFS codebase.  My question is -- has encfs4win been successfully built and tested on either Linux or OSX, or would I be safer just porting my integration changes back into ordinary EncFS?

**Comment by jetwhiz** [comment]
Hi @jon-blum 

As-is I don't believe encfs4win would port directly to Mac and Linux, since there are a few Windows-specific components and changes that are relatively pervasive throughout the code (mostly dealing with variables and libraries available).  It would likely be possible to make the codebase work directly on Linux and Mac, though keeping this support has not been a priority since there is a native version available for these versions.  

Have you attempted to make any modifications to try building the encfs4win codebase on Linux?
