### ISSUE TITLE
BUG in utf8_to_wfn function 

### ISSUE THREAD

**Issue by leochou0729** [jetwhiz/encfs4win#139]
Hello,
  I think maybe there's a bug in the utf8_to_wfn function in compatwin.cpp.
  I just copy this function code here.

  ```
std::wstring
utf8_to_wfn(const std::string& src)
{
  //VLOG(1) << "NOTIFY -- utf8_to_wfn";
  int len = src.length() + 1;
  const size_t addSpace = 6;
  std::vector<wchar_t> buf(len + addSpace);
  utf8_to_wchar_buf(src.c_str(), buf.data() + addSpace, len);
  for (wchar_t *p = buf.data() + addSpace; *p; ++p)
    if (*p == L'/')
      *p = L'\\';
  char drive = tolower(buf[addSpace]);
  if (drive >= 'a' && drive <= 'z' && buf[addSpace + 1] == ':') {
    memcpy(buf.data() + (addSpace - 4), L"\\\\?\\", 4 * sizeof(wchar_t));
    return buf.data() + (addSpace - 4);
  }
  else if (buf[addSpace] == L'\\' && buf[addSpace + 1] == L'\\') {
    memcpy(buf.data() + (addSpace - 6), L"\\\\?\\UNC", 7 * sizeof(wchar_t));
    return buf.data() + (addSpace - 6);
  }
  return buf.data() + addSpace;
}
```

You allocate 6 wchat_t space in the front of the path string, but copy 7 characters into it with L"\\\\?\\UNC".

**Comment by jetwhiz** [comment]
Hi @leochou0729 !  

I think this part of code is admittedly a little convoluted in its intentions and could use some better commenting, since we are actually clobbering the first backslash on purpose.  

https://github.com/jetwhiz/encfs4win/blob/ad8367dc540ce151ec168e27df38d3af1f60be4c/encfs/compatwin.cpp#L848-L851

Note here that we want to replace `\\` with `\\?\UNC\` (and not `\\?\UNC\\`), meaning we need to overwrite as:
````
     01234567
 IN:       \\
OUT: \\?\UNC\
````

Could you test this out just to make sure?  Also, if you could create a PR to clarify what's happening here it would be greatly appreciated!

**Comment by leochou0729** [comment]
Sorry for the misunderstanding. Thank you for clarification.
