### ISSUE TITLE
Box Drive ignore files begining with "."

### ISSUE THREAD

**Issue by sina2** [jetwhiz/encfs4win#141]
Hello ,

I wanto to  use  encfs4win on "Box Drive" . 

But I can't use this ,beause "Box Drive" ignore files begining with "."(in this case ".encfs6.xml") 

[https://community.box.com/t5/Box-Sync-Troubleshooting/File-Types-Ignored-or-Blocked-by-Box-Sync-and-Box-Drive/ta-p/117](https://community.box.com/t5/Box-Sync-Troubleshooting/File-Types-Ignored-or-Blocked-by-Box-Sync-and-Box-Drive/ta-p/117)

I want to add option ( change configuration file )

Sincerely

**Comment by jetwhiz** [comment]
Hi @sina2 

You can store your configuration file in a different location, outside of Box Drive, or name the file something else and use the `ENCFS6_CONFIG` environment variable to tell encfs4win where to find it (see: https://github.com/jetwhiz/encfs4win/blob/master/encfs/encfs.pod#environment-variables). 

Since this file has your secret encryption key stored in it, it is recommended to not have this file stored in a synced cloud for maximum security.

**Comment by sina2** [comment]
Hi @jetwhiz 

I understand  how to use the ENCFS6_CONFIG environment variable in windows.

Thank you very much for answering my question.
