### ISSUE TITLE
Standalone encfsctl without Dokan

### ISSUE THREAD

**Issue by RunasSudo** [jetwhiz/encfs4win#31]
It would be nice if `encfsctl` didn't depend on Dokan, so it could be used as a standalone application to decrypt files (through `encfsctl cat`) where Dokan is not available. I've had some limited success using a stub `dokanfuse1.dll` implementing only the necessary functions, so this should be possible.

**Comment by jetwhiz** [comment]
@RunasSudo  -- encfsctl should work fine without Dokan installed, but the dokanfuse DLL is required.  Unfortunately this dependency cannot be removed (without significantly deviating from upstream EncFS), since encfs and encfsctl are so deeply intertwined with each other.  

It appears that "encfsctl export" is broken, however.  There are a few bugs in EncFS that I will patch and release in the next version (1.10.1-RC5).  Is this what you meant by having "limited success" using dokanfuse1.dll?

**Comment by RunasSudo** [comment]
Aah, you're right. I tested it earlier and it didn't work, but I must have used the wrong architecture dokanfuse1.dll. Thanks!
