### ISSUE TITLE
No stable releases

### ISSUE THREAD

**Issue by lalomartins** [jetwhiz/encfs4win#45]
How come all releases in the list are “pre-release” and RCx? Doesn't inspire much confidence. Please add a stable release at the end of each cycle, even if it's a copy of the last RC with only the version number bumped (as it should probably be).

**Comment by jetwhiz** [comment]
HI @lalomartins 

Version 1.10.1 should be our first stable release, but I'm hoping to package Dokany v1.0 stable (which is still a RC right now).  As soon as Dokany v1.0 becomes stable then I will consider encfs4win to be stable (which will hopefully be soon).

**Comment by Zero3** [comment]
I'm concerned about marking encfs4win as "stable".

I would like to see a stable version soon just as much as you guys, but in my opinion/experience, encfs4win and dokany are just not there yet. Just a month or two ago, I reported very trivial and serious bugs like encfs4win crashing if you close the console window or press CTRL + C. And the https://github.com/jetwhiz/encfs4win/issues/32 BSOD bug is still open, alongside the (maybe identical) Dokany BSOD bug https://github.com/dokan-dev/dokany/issues/230.

It would also be nice to see some file system tests run (successfully) against mounted folders, something that has not been done yet (I think?). Such tests would add further confidence in encfs4win being "stable".

**Comment by jetwhiz** [comment]
@Zero3  -- I just noticed that the related BSOD Dokany issue is slated to their 1.1.0 release (and not their next 1.0.0 release).  I don't think it will be possible to call the "modern" release stable until this issue is resolved by Dokany.  If I'm not mistaken, though, the legacy version should be much more stable ...

**Comment by jetwhiz** [comment]
I think things have stabilized pretty well over the past year, and there haven't been any major bugs reported that would merit holding off on releasing a stable release.  I think RC12 will be (hopefully) the last release candidate before v1.10.1 is released, as long as no big issues are reported over the next few weeks.

**Comment by jetwhiz** [comment]
Hi @sergeevabc -- I'm definitely keeping an eye on moving to Dokany 2.0 (especially since many issues with encfs4win are related to performance).  This might be good to pair with the newest [encfs 1.9.2](https://github.com/vgough/encfs/releases/tag/v1.9.2).  

As soon as I release encfs4win v1.10.1 (which is based on encfs v1.9.1) I will move towards encfs v1.9.2 and then start looking at Dokany 2.0 (as it also becomes more stable).
