### ISSUE TITLE
[Question] Allow custom location for encfs6.xml in encfsw

### ISSUE THREAD

**Issue by ntt4** [jetwhiz/encfs4win#59]
# Environment
- Windows version: Windows 10 (10.0.14393)
- Processor architecture: x86_64
- Encfs4win version: 1.10.1-RC9
- Dokan version (modern)
# Description

Is it possible for encfsw to load a custom encfs6.xml via a registry key or option within the GUI?
## Expected behavior
1. Open encfsw
2. Import currently encrypted folder
3. Allow encfsw to load to a custom encfs6.xml eg ENCFS6_CONFIG=C:\encfskeys\keyone.xml

**Comment by jetwhiz** [comment]
@ntt4 -- Right now this is not possible with encfsw, but I am currently working on a more modern GUI for encfs4win that will supersede encfsw. 

In the meantime, I will see if I can throw something into encfsw to allow a custom encfs6.xml file to be used.

**Comment by ntt4** [comment]
@jetwhiz Thanks for the reply! I'll make sure to keep an eye on the project for any updates

**Comment by 4llan** [comment]
The only way to do this in GUI is setting a temp environment variable (ENCFS6_CONFIG) at the moment of subprocess creation.

[MSDN - Changing Environment Variables](https://msdn.microsoft.com/en-us/library/ms682009.aspx)

**Comment by jscottdouglas** [comment]
any chance of this getting added to atleast commandline? looks like this was opened a year ago, I am using rclone with this to just be able to quickly read my google cloud but what ends up happening is the xml is getting uploaded to the cloud, that's a security issue so i would like to use my config outside of the folder that i am mounting from

**Comment by jetwhiz** [comment]
Hi @jscottdouglas -- at least for the command line, setting the ENCFS6_CONFIG environment variable should do the trick.  See the [encfs manpage](https://github.com/jetwhiz/encfs4win/blob/master/encfs/encfs.pod#environment-variables) for more details.  

I'll check this weekend on whether this is something that can be easily added to the GUI.

**Comment by jetwhiz** [comment]
I will try to target this functionality for the 1.11.0 release, since I am afraid of breaking something at the last minute by making these changes.  I think it would definitely be useful to make the encfsw interface more powerful and flexible, though.

**Comment by amicalmant** [comment]
Just a few remarks, @ntt4, since this issue is not fixed yet. My question is: why would you want to use custom locations for your encfs6.xml files? The obvious answers is: security reasons.

Personally, I have a real time backup of my encrypted folders always running and allowing synchronization across several devices. For security reasons, I excluded the XML keys from those backups. I manually backup in a separate folder copies of those XML files renamed in such way that I can easily know which encrypted folder they belong too.

As of my security concern with backups, I think this does the trick. However, your suggestion would make it easier and safer on the local file system too.
