### ISSUE TITLE
Renaming file in root dir affects unrelated files while using Null filename encryption

### ISSUE THREAD

**Issue by vovcacik** [jetwhiz/encfs4win#83]
# Environment
 * Windows version: Windows 10 Pro
 * Processor architecture: x64
 * Encfs4win version: encfs version 1.10.1-RC10
 * Dokan version (legacy, modern): Dokany 1.0.2

# Description 
When I create encfs disk with Null filename encryption and I create empty file aaaa.txt in root dir manually (i.e. not through encfs itself) and non-empty bbbb.txt file, then two files are displayed in encfs encrypted disk a) the encfs config xml file b) aaaa.txt. When I rename bbbb.txt in root dir to `-bbbb.txt` it will cause the xml file and the aaaa.txt to disappear from the encfs disk.

## Expected behavior vs. actual behavior 
Renaming bbbb.txt should not affect aaaa.txt or other files.

## Steps to reproduce problem
Stay with default values while creating encfs disk, but choose Null filename encryption.

```
@echo off
mkdir "%temp%\bug"
encfs "%temp%\bug" x:

echo 1234 > "%temp%\bug\bbbb.txt"
type nul > "%temp%\bug\aaaa.txt"

echo Rename %temp%\bug\bbbb.txt to %temp%\bug\-bbbb.txt
pause

pause
dokanctl /u x:
rmdir /S /Q "%temp%\bug"
```

# Relevant logs
Nothing relevant in logs.

**Comment by vovcacik** [comment]
This is related to #84 but I focus on file size here, while the first focuses on file content, `<?xml ` to be precise.

**Comment by jetwhiz** [comment]
The issue here is that you have (what's supposed to be) an encrypted file that is empty and you've also used default settings, which uses per-file IVs (which expects there to be a header in the encrypted files).  When the empty file is opened it throws an assertion error, since the length of the file is less than the length of the expected header.  

I expect this is the same behavior upstream, since the related code all looks the same.  Do you know if this is true @benrubson?
