### ISSUE TITLE
Problem with caches from one OS to another

### ISSUE THREAD

**Issue by MangoMango666** [jetwhiz/encfs4win#87]
# Environment
 * Windows version: 7
 * Processor architecture: 64 bits
 * Encfs4win version: downloaded last month
 * Dokan version (legacy, modern): 

# Description 
I am trying to use Encfs caches with various OS (actually 2 OS in dual-boot on the same computer) : Linux Mint 17.3 (with Gnome Encfs Manager 1.8.18) and Windows 7 (Encfs4Win downloaded last month). The partition on which the cache is stored is NTFS.
Trouble : if I create a cache in Linux, I can open it in Windows. But if I create a cache in Windows, I cannot open it in Linux. It says "the interface for coding the requested file name is not available. [timestamp] (FileUtils.cpp.1649) Impossible to find the nameio interface nameio/block, version 4:0:0"

## Expected behavior vs. actual behavior 
One should be able to use the caches regardless from with which OS they have been created.

## Steps to reproduce problem
1. 

# Relevant logs

Attach any relevant log files that can help to debug your issue (be sure to use the -v option for verbose logs).

**Comment by jetwhiz** [comment]
Hi @MangoMango666 -- thank you for the bug report!  

Could you send me an example config file generated by both the Linux and Windows machine?  It's possible that the version of encfs that Gnome Encfs Manager uses is too old to support v4 of the Block coding cipher. 

Also, I recommend you use nameio/block32 instead of nameio/block if you plan on using this cache with both Windows and Linux.  Windows is case-insensitive, so using Block coding will likely cause issues down the line.

**Comment by MangoMango666** [comment]
Hi.
Here is attached the file from a cache create with Gnome Manager Encfs.Is that enough ?
Regards,
M.



On Thursday, July 20, 2017, 12:26:00 AM GMT+2, JetWhiz <notifications@github.com> wrote:


Hi @MangoMango666 -- thank you for the bug report!

Could you send me an example config file generated by both the Linux and Windows machine? It's possible that the version of encfs that Gnome Encfs Manager uses is too old to support v4 of the Block coding cipher.

Also, I recommend you use nameio/block32 instead of nameio/block if you plan on using this cache with both Windows and Linux. Windows is case-insensitive, so using Block coding will likely cause issues down the line.

**Comment by jetwhiz** [comment]
It looks like the attachments did not come through.  Are you able to find the config files on the Linux and Windows machines?

**Comment by MangoMango666** [comment]
Hello.
Here are the config files of both a Linux created cache and a Windows created one, zipped with 7-zip.It looks indeed as their version are not the same. Gnome Manager's config file indicates version 1.7.4 , while the config file of the cache created with Encfs4win indicates versio1.10.1-RC11. The Synaptic package manager indicates it is the latest version available in the official repositories (I am using Linux Mint 17.3). Gnome Manager Encf's version is 1.8.18, also the latest.

So the question is : will it a problem to use the same cache (version 1.7.4) with both softwares alternatively ?

On Friday, July 21, 2017, 12:35:11 AM GMT+2, JetWhiz <notifications@github.com> wrote:


It looks like the attachments did not come through. Are you able to find the config files on the Linux and Windows machines?

**Comment by MangoMango666** [comment]
Hi.
BTW, how can one delete previously set caches from the GUI of Encfs4Win ?
Manfred

On Thursday, July 20, 2017, 12:26:00 AM GMT+2, JetWhiz <notifications@github.com> wrote:


Hi @MangoMango666 -- thank you for the bug report!

Could you send me an example config file generated by both the Linux and Windows machine? It's possible that the version of encfs that Gnome Encfs Manager uses is too old to support v4 of the Block coding cipher.

Also, I recommend you use nameio/block32 instead of nameio/block if you plan on using this cache with both Windows and Linux. Windows is case-insensitive, so using Block coding will likely cause issues down the line.

**Comment by jetwhiz** [comment]
Hi @MangoMango666 ,

There might be an issue with attaching files via email, since I still do not see any files attached on the github website.  Is it possible to upload the config files via the GitHub website instead?  

Regarding deleting your caches, this can only be done manually by removing the encrypted directory.  The GUI only allows you to create and mount/unmount the caches.  I am still working on a more powerful GUI that will give more control and flexibility.

**Comment by MangoMango666** [comment]
Hi.
Sorry for the delay. Here are the config files again.
[EncfsConfFiles.zip](https://github.com/jetwhiz/encfs4win/files/1245543/EncfsConfFiles.zip)

**Comment by jetwhiz** [comment]
Thanks, @MangoMango666 !  

That does look like the issue -- Gnome Encfs Manager is built with an outdated version of encfs (1.7.4), while the latest is 1.9.1.  

You can see the difference with the nameio version number here (v3.0 vs v4.0): 

**Gnome Encfs Manager:** 
````xml
	<nameAlg>
		<name>nameio/block</name>
		<major>3</major>
		<minor>0</minor>
	</nameAlg>
````

**Encfs4win:**
````xml
        <nameAlg>
            <name>nameio/block</name>
            <major>4</major>
            <minor>0</minor>
        </nameAlg>
````

You can open it with encfs4win because it has backwards compatibility with the older version, but encfs 1.7.4 can't open the more modern format.  

A workaround might be to just create the drive with the older version (Gnome Encfs Manager) and then use it with Encfs4win, too, though this might come at the cost of security issues that have been fixed in the newer versions of encfs.  Otherwise I don't think Gnome Encfs Manager could be used without somehow forcing it to use a more modern encfs. 

I would also recommend choosing nameio/block32 instead of nameio/block though, since Windows is not case-sensitive (and nameio/block can cause issues on Windows)
