### ISSUE TITLE
[Discussion] comparison with EncFSMP

### ISSUE THREAD

**Issue by ephestione** [jetwhiz/encfs4win#88]
I understand the risk of getting bashed in here for bringing up this "issue", which clearly isn't an issue in github's terms, yet the absence of a "discussion" tab in projects doesn't really help.

So, I've been using the old enfs4win for the longest time, until I got really fed up with the way files couldn't be sometimes written to, had been locked, whatever. Then I discovered DokanY, better but not so good; then finally EncFSMP started supporting commandline mounting, so I could automount on boot my data like I did with old encfs4win, and I've switched to EncFSMP since then.

Just today I realized I could make use of the --reverse option, that EncFSMP doesn't support, and by chance I discovered that there's a rebirth of encfs4win, that comes together with DokanY nonetheless.

Apart from this obvious difference with the --reverse option, and the fact that one uses Dokan, the other PismoFileMount (open VS closed source), what would you say are the technical differences between the two?

**Comment by jetwhiz** [comment]
As far as I understand, EncFSMP is just a wrapper around the encfs software, targeting compatibility with encfs 1.7.4.  encfs4win is maintained in lock-step with the upstream encfs project, so it stays essentially the same as running encfs on *nix, and runs with the latest updates and fixes that the actual encfs project uses (1.9 right now).  

As you've already mentioned, EncFSMP also relies on closed-source software (Prismo) to function, which does not fit in line with the open source or crypto/security spirit.

**Comment by ephestione** [comment]
Another minor difference, probably due to Dokan not being able to give labels to volumes, is that any mountpoint with this is named "DOKAN (X:)" in explorer, while with EncFSMP you can give a label, maybe Pismo has this feature.

**Comment by jetwhiz** [comment]
You should be able to pass a volume name (label) into Dokany via the -o (FUSE argument) flag: 

````cmd
 encfs.exe ... -o volname="label"
````

**Comment by amicalmant** [comment]
Hey @jetwhiz! I use enfcs both in Linux Mint 18.2 (based on Ubuntu 16.04) and Windows 10 (dual boot). I used encfsMP until recently but the way you explain your security concerns and your openness have convinced me to try the switch.

Question: Can you tell me if my encrypted directory will work with your latest version and still be compatible with my Linux install?
Candy: If you're interested I can help with French text translation.

Thanks,
--
C.A.

**Comment by jetwhiz** [comment]
Hi @amicalmant 

Do you know if your Linux setup is using Block mode or Block32 mode for the filename block cipher (if you're using a block filename cipher)?  If you want to ensure compatibility with encfs4win then it is best to be operating with Block32 (since Windows' NTFS is not case-sensitive by default, which can cause quirks with some programs where it can't find some files).  

Since you're using EncfsMP, I assume your setup is also using older settings (for backward compatibility).  It might be a good idea to re-encrypt your files with Encfs 1.9 to take advantage of the latest security updates that have come with 1.9 (and choose Block32 or Stream if you want filename encryption).  Of course EncfsMP will not be able to access that filesystem anymore though, so be sure you're happy with the setup and everything works well before doing this. 

Regardless, I would recommend playing around with a test filesystem between the two first to be sure everything looks good before doing anything with your real data. 

And we would definitely appreciate any translations that can be supplied!  It might be easier for you to supply these to the upstream encfs project (https://github.com/vgough/encfs), since the main project can also benefit from this.  Since we're a fork, we can just pull in your contributions here afterwards.  

Let me know if you need any help or have questions on setting things up.

**Comment by amicalmant** [comment]
Thanks for your reply @jetwhiz. I will digest it slowly before:

1. Sharing any issues I had and things I learned following the path you have suggested here.
2. Checking the encfs project to see how I can help.

Thanks! And, by the way, that's a nice hexagonal flag that you have on your homepage. I have one of mine here: http://tlmv.ca/frenchpork (LOL)

**Comment by jetwhiz** [comment]
Thanks, @amicalmant -- keep us updated with your progress!

**Comment by amicalmant** [comment]
Oh, I forgot to follow up here, sorry about that. In fact, I did not check anything but I just installed and try to open a copy of my encrypted directory and it worked like a charm. I can read, write, and the resulting encryption is still compatible with my EncFS Linux version. That's perfect!

In regards to the French code translation I must take a look at it to see what is needed. Is there a file or a thread with some guidance? 

- Apart from the po/fr and fr_FR files, do you use a centralized translation platform or should I just clone, work on one of those files and submit for merging?

- Also, why two files? One should be enough, no?
