### ISSUE TITLE
Simplest install: dokanfuse1.dll not found

### ISSUE THREAD

**Issue by joaoe** [jetwhiz/encfs4win#89]
# Environment
 * Windows version: 10.0.15063
 * Processor architecture: x64
 * Encfs4win version: v1.10.1-RC12
 * Dokan version (legacy, modern): none

# Description 

Hi.

I used the encfs-installer.exe v1.10.1-RC12 but during installation I checked off all options but encfs, because I want a barebones local install of encfs to carry in a portable disk, which I carry with me.

While running encfs.exe I get the error "The code execution cannot proceed because dokanfuse1.dll was not found (...)".

After searching the issue tracker, I saw the issue where it's claimed that the dependency on Dokan is required always. Therefore, if it's a hard dependency, the installer should not give the option NOT to install Dokan.

## Expected behavior vs. actual behavior 
...

## Steps to reproduce problem
1. install without dokan
2. run encfs

**Comment by necrevistonnezr** [comment]
What if you have Dokan/Dokany already installed? You shouldn't be forced to install it, then.

**Comment by joaoe** [comment]
Don't know every well how to solve that. Perhaps detect during the installation process and warn the user in case it's not installed ?

**Comment by jetwhiz** [comment]
That was the original reason for making it optional, since Dokany is used for many different projects and not only encfs4win, so there's a good chance it (and maybe a different version) might already be installed.  

We can either try to detect if it is already installed and make it required if not, or add a note to the installer mentioning that it is required if not already installed.

**Comment by joaoe** [comment]
Feel free to solve as you see fit. Thank you for your time.
