### ISSUE TITLE
Error 1450: Insufficient system resources exist to complete the requested service

### ISSUE THREAD

**Issue by elieux** [jetwhiz/encfs4win#91]
# Environment
 * Windows version: Win10 1709, build 16288.1
 * Processor architecture: AMD64
 * Encfs4win version: 1.10.1-RC12
 * Dokan version (legacy, modern): modern 1.0.5

# Description 

Directory listing is interrupted if it takes too long.

## Steps to reproduce problem

1. Mount an encrypted directory.
2. On the mounted drive, open a (sub)directory with lots of entries.

## Expected behavior vs. actual behavior 

Expected: Takes some time, then finishes successfully.

Actual: Takes a fixed amount of time, then fails with the error 1450.

# Relevant logs

AFAIK this has been the case ever since the original encfs4win (I have been using that one until recently).  From what I remember about my research then, there's a timer in Dokan that will kill the callback and produce this error unless the callback postpones the deadline regularly.

A 1000 entries seems to reliably reproduce the issue on my machine.  It doesn't even have to be a long directory listing, just reading from a network (or otherwise slow) drive can make the listing slow enough.

**Comment by elieux** [comment]
It is also dependent on the filesystem cache.  After listing my 1000-entry *encrypted* directory once, the mounted one starts working just fine.

**Comment by jetwhiz** [comment]
Hi @elieux -- thanks for the bug report! 

This sounds like it might be related to the general stability issue that was reported (https://github.com/jetwhiz/encfs4win/issues/62), which may be due to the fact that Dokany thinks encfs4win has crashed while it is reading/opening files that take a while (as you mention).  Unfortunately I don't believe access to increase the timeout is available through the FUSE interface.  The closest we can get is by setting the daemon_timeout parameter.  

Can you try using "-o daemon_timeout=M" (where M is in milliseconds) on your mount and see if this helps the issue at all?  

Otherwise the Dokany 2.0 beta version (https://github.com/dokan-dev/dokany/releases/tag/v2.0.0-BETA1) will hopefully address this issue better.

**Comment by jetwhiz** [comment]
Hi @elieux 

Have you been able to confirm that this issue still exists with the latest versions of encfs4win and Dokany?  There have been a lot of stability updates in Dokany that may have helped this issue.
