### ISSUE TITLE
Silent install

### ISSUE THREAD

**Issue by starik1968** [jetwhiz/encfs4win#97]
Hello, would be nice if it would be possible to install silently and without restart.

Thx

cu starik1968

**Comment by amicalmant** [comment]
Hey, man, if you want to install low level software or system updates without rebooting your computer you should seriously consider using Linux as your main operating system (if it's not done yet). I live much more easily with Windows flaws since I have switched 7 years ago. ;-)

**Comment by starik1968** [comment]
Hi jetwhiz, 

figured it out how. 

Unpacked the installer with 7Zip and installed dokany with /norestart. 

Did not install the VC Redist 'coz I have 2015 on my PC.  /norestart should work there also, AFAIK it is a standard installer switch with MS-Installers.

Have a very special using screnario: Reset my PC daily and don't want the software inside my image, but want to use it if I want. 

Seems like it runs, but had to test it. 

Surely a very special case. But it would be fine if the installers warns about the restart, first time I tried the software it restarted and I had a lot of programs open. Love the software, it is what I searched for a while.

**Comment by jetwhiz** [comment]
Hey @starik1968 

You're right, it looks like /quiet mode will automatically restart with the Windows installers without prompting.  I think I will change these to either "/passive /promptrestart" or "/quiet /norestart" for the next beta release.  

Since this is a similar issue to https://github.com/jetwhiz/encfs4win/issues/96 I'm going to close this one so we can keep everything on one issue thread, but you can track the status of this bug from there.
